### ISSUE TITLE
MyBot 不能登陆

### ISSUE THREAD

**Issue by yunjuanai** [HanSon/my-vbot#1]
[2017-06-23 12:41:54][INFO] please scan the qrCode with wechat.
[2017-06-23 12:42:04][INFO] please confirm login in wechat.
[2017-06-23 12:42:07] vbot.ERROR: ����Ŀ�����������ܾ����޷���ӡ� [tcp://127.0.0.1:6379] [] []
PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: ����Ŀ�����������ܾ����޷���ӡ� [tcp://127.0.0.1:6379] in E:\erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.
php:155
Stack trace:
#0 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('\xD3\xC9\xD3\xDA\xC4\xBF\xB1\xEA\xBC\xC6\xCB\xE3\xBB\xFA\xBB...', 10061)
#1 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4)
#2 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#3 E:\erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(258): Predis\Connection\AbstractConnection->co in E:\erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.php on line 155
[2017-06-23 12:42:07] vbot.ERROR: Uncaught Predis\Connection\ConnectionException: ����Ŀ�����������ܾ����޷���ӡ� [tcp://127.0.0.1:6379] in E:\erp\wbot\vendor\predis\predis\src\Connection\Abs
tractConnection.php:155 Stack trace: #0 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('\xD3\xC9\xD3\xDA\xC4\xBF\xB1\xEA\xBC\xC6\xCB\xE3\xBB\xFA\xBB...', 10061) #1 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4) #2 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters)) #3 E:\erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource() #4 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(258): Predis\Connection\AbstractConnection->co [] []
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Predis\Connection\ConnectionException: ����Ŀ�����������ܾ����޷���ӡ� [tcp://127.0.0.1:6379] in E:\
erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.php:155
Stack trace:
#0 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('\xD3\xC9\xD3\xDA\xC4\xBF\xB1\xEA\xBC\xC6\xCB\xE3\xBB\xFA\xBB...', 10061)
#1 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4)
#2 E:\erp\wbot\vendor\predis\predis\src\Connection\StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#3 E:\erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()
#4 E:\erp\wbot\vendor\predis\predis\src\Connection\Str in E:\erp\wbot\vendor\predis\predis\src\Connection\AbstractConnection.php on line 155

**Comment by Hanson** [comment]
这是因为你开启了 redis 缓存但配置不正确
